// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Runtime.InteropServices;

namespace TasksApi
{
    public partial class Worker
    {
        public int workerId { get; set; }

        [StringLength(50, MinimumLength = 5), Required]
        public string forename { get; set; }

        [StringLength(50, MinimumLength = 5), Required]
        public string surname { get; set; }

        [StringLength(50), Required]
        public string email { get; set; }

        [DataType(DataType.Date)]
        public DateTime dob { get; set; }
    }
}